/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paco
 */
public class Prestamo extends javax.swing.JInternalFrame {

    int codPrestamo;

    String fechaLimite;

    public Prestamo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Anio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        mes = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        Anio1 = new javax.swing.JTextField();
        mes1 = new javax.swing.JTextField();
        dia1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        Limpiar = new javax.swing.JLabel();
        Save = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Ingrese código libro:");

        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel3.setText("Fecha Prestamo:");

        Anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AnioKeyTyped(evt);
            }
        });

        jLabel4.setText("ID usuario:");

        idU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idUKeyTyped(evt);
            }
        });

        jLabel7.setText("Fecha Límite:");

        jLabel2.setText("Estado:");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Malo", " " }));

        mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesKeyTyped(evt);
            }
        });

        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaKeyTyped(evt);
            }
        });

        Anio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Anio1KeyTyped(evt);
            }
        });

        mes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mes1KeyTyped(evt);
            }
        });

        dia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dia1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Anio1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(mes1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idU))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(Anio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PrestamoDev.png"))); // NOI18N

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-150192_960_720.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clean-android-limpiar-logo.png"))); // NOI18N
        Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarMouseClicked(evt);
            }
        });

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Metro-Save-Blue-256.png"))); // NOI18N
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Save)
                                .addGap(18, 18, 18)
                                .addComponent(Limpiar)
                                .addGap(18, 18, 18)
                                .addComponent(salir))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Limpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Save, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_LimpiarMouseClicked

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed

    }//GEN-LAST:event_codigoKeyPressed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char a = evt.getKeyChar();

        if (a < '0' || a > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_codigoKeyTyped

    private void codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyReleased

        Recuperar();


    }//GEN-LAST:event_codigoKeyReleased

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        try {
            Conexion c = new Conexion();
            PreparedStatement ps = null, ps2 = null, ps3 = null;
            ResultSet rs = null, rs2 = null;
            Connection con = c.getConexion();
            ResultSetMetaData rsmd, rsmd2;
            int re = 0;
            ValidacionFecha fecha, fecha2;
            fecha = new ValidacionFecha(Integer.parseInt(dia.getText()), Integer.parseInt(mes.getText()), Integer.parseInt(Anio.getText()));
            fecha2 = new ValidacionFecha(Integer.parseInt(dia1.getText()), Integer.parseInt(mes1.getText()), Integer.parseInt(Anio1.getText()));
            String formato = Anio.getText() + "-" + mes.getText() + "-" + dia.getText();
            String formato2 = Anio1.getText() + "-" + mes1.getText() + "-" + dia1.getText();
           
            
            if (fecha.FechaCorrecta() && fecha2.FechaCorrecta()) {
                //Recuperando codigo del libro para saber si se  ya ha sido prestado
                String cod = "SELECT Prestado FROM detalles WHERE cod_Libro=" + "'" + codigo.getText() + "'";
                ps = con.prepareStatement(cod);
                rs = ps.executeQuery();
                rsmd = rs.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                Object[] filas = new Object[cantColumnas];
                while (rs.next()) {
                    filas[0] = rs.getObject(1);
                }

                String prs = (String) filas[0];
               
                if (prs != null) {
                    if (prs.equalsIgnoreCase("S")) {
                        JOptionPane.showMessageDialog(null, "Ejemplar en estado de prestamo.", "Advertencia", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    String query1 = "INSERT INTO prestamo(Id_Usuario,fecha_prestamo,fecha_limite) VALUES(?,?,?)";
                    String query2 = "INSERT INTO detalles(cod_Prestamo,Id_Usuario,cod_Libro,Estado,Prestado) VALUES(?,?,?,?,?)";

                    //Llenado prestamo
                    ps3 = con.prepareStatement(query1);
                    ps3.setString(1, idU.getText());
                    ps3.setString(2, formato);
                    ps3.setString(3, formato2);

                    re = ps3.executeUpdate();

                    //Recuperar codigo Prestamo
                    String queryG = "SELECT * FROM prestamo";

                    ps3 = con.prepareStatement(queryG);
                    rs2 = ps3.executeQuery();

                    rsmd2 = rs2.getMetaData();
                    int cantColumnas1 = rsmd2.getColumnCount();
                    Object[] filas1 = new Object[cantColumnas1];
                    while (rs2.next()) {
                        filas1[0] = rs2.getObject(1);

                    }//while
                    codPrestamo = (Integer) filas1[0];
                    String Prestado = "S";
                    //Llenado detalles 
                    String estado = (String) combo.getSelectedItem();
                    ps2 = con.prepareStatement(query2);
                    ps2.setString(1, String.valueOf(codPrestamo));//codigo prestamo
                    ps2.setString(2, idU.getText());
                    ps2.setString(3, codigo.getText());
                    ps2.setString(4, estado);
                    ps2.setString(5, Prestado);
                    ps2.executeUpdate();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Fecha incorrecta.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
            
            if (re > 0) {
                JOptionPane.showMessageDialog(this, "Datos guardados");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar.", "Advertencia", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
            con.close();

        } catch (Exception ex) {
            System.out.println("Excepcion: " + ex);
        }


    }//GEN-LAST:event_SaveMouseClicked

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void idUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUKeyTyped

    }//GEN-LAST:event_idUKeyTyped

    private void AnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnioKeyTyped
        int limite = 4;
        if (Anio.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_AnioKeyTyped

    private void mesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesKeyTyped
        int limite = 2;
        if (mes.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_mesKeyTyped

    private void diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyTyped
        int limite = 2;
        if (dia.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_diaKeyTyped

    private void Anio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Anio1KeyTyped
        int limite = 4;
        if (Anio1.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_Anio1KeyTyped

    private void mes1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mes1KeyTyped
        int limite = 2;
        if (mes1.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_mes1KeyTyped

    private void dia1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dia1KeyTyped
        // TODO add your handling code here:
        int limite = 2;
        if (dia1.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_dia1KeyTyped

    private void diaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyReleased

    }//GEN-LAST:event_diaKeyReleased

    public void limpiar() {
        nombre.setText("");
        codigo.setText("");
        Anio.setText("");
        dia.setText("");
        mes.setText("");
        Anio1.setText("");
        mes1.setText("");
        dia1.setText("");
        idU.setText("");

    }

    public void Recuperar() {
        Conexion c = new Conexion();
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            int cod = Integer.parseInt(codigo.getText());
            String queryG = "SELECT * FROM Libro WHERE cod_Libro=" + cod;

            Connection con = c.getConexion();
            ps = con.prepareStatement(queryG);
            rs = ps.executeQuery();

            ResultSetMetaData rsmd;

            rsmd = rs.getMetaData();
            int cantColumnas = rsmd.getColumnCount();
            Object[] filas = new Object[cantColumnas];
            while (rs.next()) {

                for (int i = 0; i < cantColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }//for

            }//while
            int p = (Integer) filas[0];
            if (cod == p) {
                nombre.setText(filas[1] + "");
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Anio;
    private javax.swing.JTextField Anio1;
    private javax.swing.JLabel Limpiar;
    private javax.swing.JLabel Save;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField dia;
    public javax.swing.JTextField dia1;
    private javax.swing.JTextField idU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField mes1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
