/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paco
 */
public class Reporte_Libro extends javax.swing.JInternalFrame {

    Conexion c = new Conexion();
    PreparedStatement ps;
    ResultSet res;

    public Reporte_Libro() {
        initComponents();
        
        codigo.setEnabled(false);
        nom.setEnabled(false);
        cat.setEnabled(false);
RepGeneral();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rGeneral = new javax.swing.JRadioButton();
        rNombre = new javax.swing.JRadioButton();
        rCategoria = new javax.swing.JRadioButton();
        rCodigo = new javax.swing.JRadioButton();
        codigo = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        cat = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        limpiar = new javax.swing.JLabel();
        reporte = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Año", "Autor", "Editorial", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libros.png"))); // NOI18N

        buttonGroup1.add(rGeneral);
        rGeneral.setSelected(true);
        rGeneral.setText("General");
        rGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rGeneralMouseClicked(evt);
            }
        });

        buttonGroup1.add(rNombre);
        rNombre.setText("Nombre");
        rNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rNombreMouseClicked(evt);
            }
        });
        rNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rCategoria);
        rCategoria.setText("Categoria");
        rCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rCategoriaMouseClicked(evt);
            }
        });

        buttonGroup1.add(rCodigo);
        rCodigo.setText("Código");
        rCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rCodigoMouseClicked(evt);
            }
        });
        rCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCodigoActionPerformed(evt);
            }
        });

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo)
                            .addComponent(nom)
                            .addComponent(cat))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(rGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCodigo)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNombre)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCategoria)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-150192_960_720.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clean-android-limpiar-logo.png"))); // NOI18N
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarMouseClicked(evt);
            }
        });

        reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteMouseClicked(evt);
            }
        });

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/elm.png"))); // NOI18N
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reporte)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(limpiar)
                    .addComponent(Eliminar)
                    .addComponent(reporte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNombreActionPerformed

    private void rCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rCodigoActionPerformed

    private void rCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rCodigoMouseClicked
        codigo.setEnabled(true);
        nom.setText(null);
        nom.setEnabled(false);
        cat.setText(null);
        cat.setEnabled(false);
    }//GEN-LAST:event_rCodigoMouseClicked

    private void rNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rNombreMouseClicked
        codigo.setEnabled(false);
        nom.setEnabled(true);
        cat.setEnabled(false);
        codigo.setText(null);
        cat.setText(null);
    }//GEN-LAST:event_rNombreMouseClicked

    private void rCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rCategoriaMouseClicked
        codigo.setEnabled(false);
        nom.setEnabled(false);
        codigo.setText(null);
        nom.setText(null);
        cat.setEnabled(true);
    }//GEN-LAST:event_rCategoriaMouseClicked

    private void rGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rGeneralMouseClicked
        codigo.setEnabled(false);
        nom.setEnabled(false);
        cat.setEnabled(false);
        codigo.setText(null);
        nom.setText(null);
        cat.setText(null);
    }//GEN-LAST:event_rGeneralMouseClicked

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarMouseClicked
        DefaultTableModel dtm = new DefaultTableModel();
        Tabla.setModel(dtm);
        try{
        ResultSetMetaData rsmd = res.getMetaData();
        int cantColumnas = rsmd.getColumnCount();
                dtm.addColumn("Codigo");
                dtm.addColumn("Titulo");
                dtm.addColumn("Año");
                dtm.addColumn("Autor");
                dtm.addColumn("Editorial");
                dtm.addColumn("Categoria");
        while (res.next()) {
            Object[] filas = new Object[cantColumnas];
            for (int i = 0; i < cantColumnas; i++) {
                filas[i] = "";
            }
            dtm.addRow(filas);
        }
        }catch(Exception ex){
            System.out.println(ex);}
    }//GEN-LAST:event_limpiarMouseClicked

    private void reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteMouseClicked
       try {
            if (rGeneral.isSelected()) {
               RepGeneral();
            }//if general
            if (rCodigo.isSelected()) {
                DefaultTableModel dtm = new DefaultTableModel();
                Tabla.setModel(dtm);
                
                String query = "SELECT * FROM Libro WHERE cod_libro=" + codigo.getText();
                Connection con = c.getConexion();
                ps = con.prepareStatement(query);
                res = ps.executeQuery();

                ResultSetMetaData rsmd = res.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                dtm.addColumn("Código");
                dtm.addColumn("Titulo");
                dtm.addColumn("Año");
                dtm.addColumn("Autor");
                dtm.addColumn("Editorial");
                dtm.addColumn("Categoria");
                while (res.next()) {
                    Object[] filas = new Object[cantColumnas];
                    for (int i = 0; i < cantColumnas; i++) {
                        filas[i] = res.getObject(i + 1);
                    }//for
                    dtm.addRow(filas);
                }//while
            }//if codigo
            if (rCategoria.isSelected()) {
                DefaultTableModel dtm = new DefaultTableModel();
                Tabla.setModel(dtm);
                
                
                String queryC= "SELECT * FROM Libro WHERE Categoria='"+cat.getText()+"'";
                Connection con = c.getConexion();
                ps = con.prepareStatement(queryC);
                res = ps.executeQuery();

                ResultSetMetaData rsmd = res.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                dtm.addColumn("Código");
                dtm.addColumn("Titulo");
                dtm.addColumn("Año");
                dtm.addColumn("Autor");
                dtm.addColumn("Editorial");
                dtm.addColumn("Categoria");
                while (res.next()) {
                    Object[] filas = new Object[cantColumnas];
                    for (int i = 0; i < cantColumnas; i++) {
                        filas[i] = res.getObject(i + 1);
                    }//for
                    dtm.addRow(filas);
                }//while
            }//if categoria
            if (rNombre.isSelected()) {
                DefaultTableModel dtm = new DefaultTableModel();
                Tabla.setModel(dtm);
                
                String queryN = "SELECT * FROM Libro WHERE Titulo=" + "'" + nom.getText() + "'";
                Connection con = c.getConexion();
                ps = con.prepareStatement(queryN);
                res = ps.executeQuery();

                ResultSetMetaData rsmd = res.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                 dtm.addColumn("Código");
                dtm.addColumn("Titulo");
                dtm.addColumn("Año");
                dtm.addColumn("Autor");
                dtm.addColumn("Editorial");
                dtm.addColumn("Categoria");
                while (res.next()) {
                    Object[] filas = new Object[cantColumnas];
                    for (int i = 0; i < cantColumnas; i++) {
                        filas[i] = res.getObject(i + 1);
                    }//for
                    dtm.addRow(filas);
                }//while
            }//if nombre

        } catch (Exception ex) { 
            System.out.println(ex);
        }
    }//GEN-LAST:event_reporteMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
      
        try {
            DefaultTableModel dtm=new DefaultTableModel();
            Connection con = c.getConexion();
            int fila = Tabla.getSelectedRow();
            String id = Tabla.getValueAt(fila, 0).toString();
            ps = con.prepareStatement("DELETE FROM Libro WHERE cod_Libro=?");
            ps.setString(1, id);
            ps.executeUpdate();
            dtm.removeRow(fila);
            JOptionPane.showInternalMessageDialog(null, "Libro eliminado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Libro con referencias a prestamos","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_EliminarMouseClicked
   public void RepGeneral(){
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            Tabla.setModel(dtm);
            
            String queryG = "SELECT * FROM Libro";
            Connection con = c.getConexion();
            ps = con.prepareStatement(queryG);
            res = ps.executeQuery();
            
            ResultSetMetaData rsmd = res.getMetaData();
            int cantColumnas = rsmd.getColumnCount();
            dtm.addColumn("Código");
            dtm.addColumn("Titulo");
            dtm.addColumn("Año");
            dtm.addColumn("Autor");
            dtm.addColumn("Editorial");
            dtm.addColumn("Categoria");
            while (res.next()) {
                Object[] filas = new Object[cantColumnas];
                for (int i = 0; i < cantColumnas; i++) {
                    filas[i] = res.getObject(i + 1);
                }//for
                dtm.addRow(filas);
            }//while
        } catch (SQLException ex) {
            Logger.getLogger(Reporte_Libro.class.getName()).log(Level.SEVERE, null, ex);
        }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eliminar;
    private javax.swing.JTable Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cat;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel limpiar;
    private javax.swing.JTextField nom;
    private javax.swing.JRadioButton rCategoria;
    private javax.swing.JRadioButton rCodigo;
    private javax.swing.JRadioButton rGeneral;
    private javax.swing.JRadioButton rNombre;
    private javax.swing.JLabel reporte;
    // End of variables declaration//GEN-END:variables
}
