/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paco
 */
public class Reporte_Usuario extends javax.swing.JInternalFrame {

    PreparedStatement ps;
    ResultSet res;
    Conexion c = new Conexion();
    Connection con;
    LinkedList<Usuario> lu;

    public Reporte_Usuario(LinkedList lu) {

        lu = new LinkedList();

        this.lu = lu;

        initComponents();
        idU.setEnabled(false);
        Nom.setEnabled(false);
        con = c.getConexion();
        RepGeneral();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelT = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rGeneral = new javax.swing.JRadioButton();
        rID = new javax.swing.JRadioButton();
        rNom = new javax.swing.JRadioButton();
        idU = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Elim = new javax.swing.JLabel();
        limp = new javax.swing.JLabel();
        salir1 = new javax.swing.JLabel();
        Reporte = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id usuario", "Nombre", "Domicilio", "Telefono", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout panelTLayout = new javax.swing.GroupLayout(panelT);
        panelT.setLayout(panelTLayout);
        panelTLayout.setHorizontalGroup(
            panelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelTLayout.setVerticalGroup(
            panelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user (1).png"))); // NOI18N

        jLabel1.setText("Tipos de reporte:");

        buttonGroup1.add(rGeneral);
        rGeneral.setSelected(true);
        rGeneral.setText("General");
        rGeneral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rGeneralItemStateChanged(evt);
            }
        });
        rGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rGeneralMouseClicked(evt);
            }
        });
        rGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGeneralActionPerformed(evt);
            }
        });

        buttonGroup1.add(rID);
        rID.setText("Id Usuario");
        rID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rIDMouseClicked(evt);
            }
        });
        rID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rNom);
        rNom.setText("Nombre");
        rNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rNomMouseClicked(evt);
            }
        });

        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rGeneral)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rID)
                                    .addComponent(rNom))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idU, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rGeneral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rID)
                            .addComponent(idU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rNom))
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Elim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/51418.png"))); // NOI18N
        Elim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElimMouseClicked(evt);
            }
        });

        limp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clean-android-limpiar-logo.png"))); // NOI18N
        limp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpMouseClicked(evt);
            }
        });

        salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close-150192_960_720.png"))); // NOI18N
        salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir1MouseClicked(evt);
            }
        });

        Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        Reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Elim)
                .addGap(18, 18, 18)
                .addComponent(limp)
                .addGap(18, 18, 18)
                .addComponent(salir1)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jSeparator1)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salir1)
                            .addComponent(limp))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Elim)
                            .addComponent(Reporte))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void rGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rGeneralActionPerformed

    private void rIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rIDActionPerformed

    private void rGeneralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rGeneralItemStateChanged

    }//GEN-LAST:event_rGeneralItemStateChanged

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomActionPerformed

    private void rIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rIDMouseClicked
        idU.setEnabled(true);
        Nom.setEnabled(false);
        Nom.setEnabled(false);
    }//GEN-LAST:event_rIDMouseClicked

    private void rNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rNomMouseClicked
        idU.setEnabled(false);
        Nom.setEnabled(true);
        idU.setText(null);
    }//GEN-LAST:event_rNomMouseClicked

    private void rGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rGeneralMouseClicked
        idU.setEnabled(false);
        Nom.setEnabled(false);
        idU.setText(null);
        Nom.setText(null);
    }//GEN-LAST:event_rGeneralMouseClicked

    private void salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salir1MouseClicked

    private void limpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpMouseClicked
        DefaultTableModel dtm = new DefaultTableModel();
        Tabla.setModel(dtm);
        try {

            ResultSetMetaData rsmd = res.getMetaData();
            int cantColumnas = rsmd.getColumnCount();
            dtm.addColumn("Id Usuario");
            dtm.addColumn("Nombre");
            dtm.addColumn("Domicilio");
            dtm.addColumn("Telefono");
            dtm.addColumn("Edad");
            while (res.next()) {
                Object[] filas = new Object[cantColumnas];
                for (int i = 0; i < cantColumnas; i++) {
                    filas[i] = "";
                }
                dtm.addRow(filas);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_limpMouseClicked

    private void ElimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElimMouseClicked
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            Connection con = c.getConexion();
            int fila = Tabla.getSelectedRow();
            String id = Tabla.getValueAt(fila, 0).toString();
            ps = con.prepareStatement("DELETE FROM usuario WHERE Id_Usuario=?");
            ps.setString(1, id);
            ps.executeUpdate();

            dtm.removeRow(fila);
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null,"Usuario con referencias a prestamos","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ElimMouseClicked

    private void ReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteMouseClicked
        try {

            if (rGeneral.isSelected()) {
               RepGeneral();
            }//if rGeneral
            if (rID.isSelected()) {
                DefaultTableModel dtm = new DefaultTableModel();
                Tabla.setModel(dtm);
                String query = "SELECT * FROM usuario WHERE id_Usuario=" + idU.getText();
                Connection con = c.getConexion();
                ps = con.prepareStatement(query);
                res = ps.executeQuery();

                ResultSetMetaData rsmd = res.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                dtm.addColumn("Id Usuario");
                dtm.addColumn("Nombre");
                dtm.addColumn("Domicilio");
                dtm.addColumn("Telefono");
                dtm.addColumn("Edad");
                while (res.next()) {
                    Object[] filas = new Object[cantColumnas];
                    for (int i = 0; i < cantColumnas; i++) {
                        filas[i] = res.getObject(i + 1);
                    }
                    dtm.addRow(filas);
                }
            }//if id
            if (rNom.isSelected()) {
                DefaultTableModel dtm = new DefaultTableModel();
                Tabla.setModel(dtm);
                String query = "SELECT * FROM usuario WHERE nombre=" + "'" + Nom.getText() + "'";
                Connection con = c.getConexion();
                ps = con.prepareStatement(query);
                res = ps.executeQuery();

                ResultSetMetaData rsmd = res.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                dtm.addColumn("Id Usuario");
                dtm.addColumn("Nombre");
                dtm.addColumn("Domicilio");
                dtm.addColumn("Telefono");
                dtm.addColumn("Edad");
                while (res.next()) {
                    Object[] filas = new Object[cantColumnas];
                    for (int i = 0; i < cantColumnas; i++) {
                        filas[i] = res.getObject(i + 1);
                    }
                    dtm.addRow(filas);
                }
            }//if nombre

        } catch (Exception ex) {
            System.out.println(ex);
        }//catch
    }//GEN-LAST:event_ReporteMouseClicked

    public void RepGeneral() {
        try{
        DefaultTableModel dtm = new DefaultTableModel();
            Tabla.setModel(dtm);
            
            String query = "SELECT * FROM usuario";
            
            ps = con.prepareStatement(query);
            res = ps.executeQuery();
            
            ResultSetMetaData rsmd = res.getMetaData();
            int cantColumnas = rsmd.getColumnCount();
            dtm.addColumn("Id Usuario");
            dtm.addColumn("Nombre");
            dtm.addColumn("Domicilio");
            dtm.addColumn("Telefono");
            dtm.addColumn("Edad");
            while (res.next()) {
                Object[] filas = new Object[cantColumnas];
                for (int i = 0; i < cantColumnas; i++) {
                    filas[i] = res.getObject(i + 1);
                }
                dtm.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Reporte_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Elim;
    private javax.swing.JTextField Nom;
    private javax.swing.JLabel Reporte;
    private javax.swing.JTable Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel limp;
    private javax.swing.JPanel panelT;
    private javax.swing.JRadioButton rGeneral;
    private javax.swing.JRadioButton rID;
    private javax.swing.JRadioButton rNom;
    private javax.swing.JLabel salir1;
    // End of variables declaration//GEN-END:variables
}
